# Generated by Django 4.0.4 on 2022-04-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Proff.', 'Mr.'), ('Proff.', 'Proff.')], max_length=7)),
                ('full_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('site', models.CharField(blank=True, max_length=25)),
                ('degree', models.CharField(blank=True, max_length=30)),
                ('freelance', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal')),
            ],
        ),
        migrations.CreateModel(
            name='ProfExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=25)),
                ('company', models.CharField(max_length=25)),
                ('start', models.CharField(max_length=4)),
                ('end', models.CharField(max_length=4)),
                ('description1', models.TextField(max_length=100)),
                ('description2', models.TextField(blank=True, max_length=100, null=True)),
                ('description3', models.TextField(blank=True, max_length=100, null=True)),
                ('description4', models.TextField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal')),
            ],
        ),
        migrations.CreateModel(
            name='OtherTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=25)),
                ('start', models.CharField(max_length=4)),
                ('end', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('listening', models.CharField(choices=[('N/A', 'N/A'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=13)),
                ('reading', models.CharField(choices=[('N/A', 'N/A'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=13)),
                ('speaking', models.CharField(choices=[('N/A', 'N/A'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=13)),
                ('writing', models.CharField(choices=[('N/A', 'N/A'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=15)),
                ('Description', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=50, upload_to='')),
                ('Description', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=25)),
                ('start', models.CharField(max_length=4)),
                ('end', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description1', models.TextField(max_length=100)),
                ('description2', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal')),
            ],
        ),
    ]
